
//////////////////////////////////////////////////
//  SecureBridge Components
//  Copyright © 2007-2021 Devart. All right reserved.
//////////////////////////////////////////////////

{$I SB.inc}
unit ScSFTPConsts;

interface

const
  // SFTP packet type
  SSH_FXP_INIT           = 1;
  SSH_FXP_VERSION        = 2;
  SSH_FXP_OPEN           = 3;
  SSH_FXP_CLOSE          = 4;
  SSH_FXP_READ           = 5;
  SSH_FXP_WRITE          = 6;
  SSH_FXP_LSTAT          = 7;
  SSH_FXP_FSTAT          = 8;
  SSH_FXP_SETSTAT        = 9;
  SSH_FXP_FSETSTAT       = 10;
  SSH_FXP_OPENDIR        = 11;
  SSH_FXP_READDIR        = 12;
  SSH_FXP_REMOVE         = 13;
  SSH_FXP_MKDIR          = 14;
  SSH_FXP_RMDIR          = 15;
  SSH_FXP_REALPATH       = 16;
  SSH_FXP_STAT           = 17;
  SSH_FXP_RENAME         = 18;
  SSH_FXP_READLINK       = 19;
  SSH_FXP_SYMLINK        = 20;
  SSH_FXP_LINK           = 21;
  SSH_FXP_BLOCK          = 22;
  SSH_FXP_UNBLOCK        = 23;
  SSH_FXP_STATUS         = 101;
  SSH_FXP_HANDLE         = 102;
  SSH_FXP_DATA           = 103;
  SSH_FXP_NAME           = 104;
  SSH_FXP_ATTRS          = 105;
  SSH_FXP_EXTENDED       = 200;
  SSH_FXP_EXTENDED_REPLY = 201;

  // Open file mask (ver 3)
  SSH_FXF_READ   = $00000001;
  SSH_FXF_WRITE  = $00000002;
  SSH_FXF_APPEND = $00000004;
  SSH_FXF_CREAT  = $00000008;
  SSH_FXF_TRUNC  = $00000010;
  SSH_FXF_EXCL   = $00000020;
  SSH_FXF_TEXT   = $00000040;

  // Open file flags
  SSH_FXF_ACCESS_DISPOSITION      = $00000007;
  SSH_FXF_CREATE_NEW              = $00000000;
  SSH_FXF_CREATE_TRUNCATE         = $00000001;
  SSH_FXF_OPEN_EXISTING           = $00000002;
  SSH_FXF_OPEN_OR_CREATE          = $00000003;
  SSH_FXF_TRUNCATE_EXISTING       = $00000004;
  SSH_FXF_APPEND_DATA             = $00000008;
  SSH_FXF_APPEND_DATA_ATOMIC      = $00000010;
  SSH_FXF_TEXT_MODE               = $00000020;
  SSH_FXF_BLOCK_READ              = $00000040;
  SSH_FXF_BLOCK_WRITE             = $00000080;
  SSH_FXF_BLOCK_DELETE            = $00000100;
  SSH_FXF_BLOCK_ADVISORY          = $00000200;
  SSH_FXF_NOFOLLOW                = $00000400;
  SSH_FXF_DELETE_ON_CLOSE         = $00000800;
  SSH_FXF_ACCESS_AUDIT_ALARM_INFO = $00001000;
  SSH_FXF_ACCESS_BACKUP           = $00002000;
  SSH_FXF_BACKUP_STREAM           = $00004000;
  SSH_FXF_OVERRIDE_OWNER          = $00008000;

  // valid-attribute-flags
  SSH_FILEXFER_ATTR_SIZE              = $00000001;
  SSH_FILEXFER_ATTR_UIDGID            = $00000002;
  SSH_FILEXFER_ATTR_PERMISSIONS       = $00000004;
  SSH_FILEXFER_ATTR_ACMODTIME         = $00000008;
  SSH_FILEXFER_ATTR_ACCESSTIME        = $00000008;
  SSH_FILEXFER_ATTR_CREATETIME        = $00000010;
  SSH_FILEXFER_ATTR_MODIFYTIME        = $00000020;
  SSH_FILEXFER_ATTR_ACL               = $00000040;
  SSH_FILEXFER_ATTR_OWNERGROUP        = $00000080;
  SSH_FILEXFER_ATTR_SUBSECOND_TIMES   = $00000100;
  SSH_FILEXFER_ATTR_BITS              = $00000200;
  SSH_FILEXFER_ATTR_ALLOCATION_SIZE   = $00000400;
  SSH_FILEXFER_ATTR_TEXT_HINT         = $00000800;
  SSH_FILEXFER_ATTR_MIME_TYPE         = $00001000;
  SSH_FILEXFER_ATTR_LINK_COUNT        = $00002000;
  SSH_FILEXFER_ATTR_UNTRANSLATED_NAME = $00004000;
  SSH_FILEXFER_ATTR_CTIME             = $00008000;
  SSH_FILEXFER_ATTR_EXTENDED          = $80000000;

  AllowedAttributesVersion3 =
    SSH_FILEXFER_ATTR_SIZE or SSH_FILEXFER_ATTR_UIDGID or
    SSH_FILEXFER_ATTR_PERMISSIONS or SSH_FILEXFER_ATTR_ACMODTIME or
    SSH_FILEXFER_ATTR_EXTENDED;

  AllowedAttributesVersion4 =
    SSH_FILEXFER_ATTR_SIZE or SSH_FILEXFER_ATTR_PERMISSIONS or
    SSH_FILEXFER_ATTR_ACCESSTIME or SSH_FILEXFER_ATTR_CREATETIME or
    SSH_FILEXFER_ATTR_MODIFYTIME or SSH_FILEXFER_ATTR_ACL or
    SSH_FILEXFER_ATTR_OWNERGROUP or SSH_FILEXFER_ATTR_SUBSECOND_TIMES or
    SSH_FILEXFER_ATTR_EXTENDED;

  AllowedAttributesVersion5 = AllowedAttributesVersion4 or
    SSH_FILEXFER_ATTR_BITS;

  AllowedAttributesVersion6 = AllowedAttributesVersion5 or
    SSH_FILEXFER_ATTR_ALLOCATION_SIZE or SSH_FILEXFER_ATTR_TEXT_HINT or
    SSH_FILEXFER_ATTR_MIME_TYPE or SSH_FILEXFER_ATTR_LINK_COUNT or
    SSH_FILEXFER_ATTR_UNTRANSLATED_NAME or SSH_FILEXFER_ATTR_CTIME;

  // File types
  SSH_FILEXFER_TYPE_REGULAR      = 1;
  SSH_FILEXFER_TYPE_DIRECTORY    = 2;
  SSH_FILEXFER_TYPE_SYMLINK      = 3;
  SSH_FILEXFER_TYPE_SPECIAL      = 4;
  SSH_FILEXFER_TYPE_UNKNOWN      = 5;
  SSH_FILEXFER_TYPE_SOCKET       = 6;
  SSH_FILEXFER_TYPE_CHAR_DEVICE  = 7;
  SSH_FILEXFER_TYPE_BLOCK_DEVICE = 8;
  SSH_FILEXFER_TYPE_FIFO         = 9;

  // POSIX Flags
  S_IFMT  = $000F000;    // mask for the file type
  {$EXTERNALSYM S_IFMT}
  S_IFSOCK= $000C000;    // socket
  {$EXTERNALSYM S_IFSOCK}
  S_IFLNK = $000A000;    // symbolic link
  {$EXTERNALSYM S_IFLNK}
  S_IFREG = $0008000;    // regular file
  {$EXTERNALSYM S_IFREG}
  S_IFBLK = $0006000;    // block device
  {$EXTERNALSYM S_IFBLK}
  S_IFDIR = $0004000;    // directory
  {$EXTERNALSYM S_IFDIR}
  S_IFCHR = $0002000;    // character device
  {$EXTERNALSYM S_IFCHR}
  S_IFIFO = $0001000;    // FIFO
  {$EXTERNALSYM S_IFIFO}

  // Permissions
  S_ISUID = $0000800;
  {$EXTERNALSYM S_ISUID}
  S_ISGID = $0000400;
  {$EXTERNALSYM S_ISGID}
  S_ISVTX = $0000200;
  {$EXTERNALSYM S_ISVTX}

  S_IRWXU = $00001C0;    // mask for file owner permissions
  {$EXTERNALSYM S_IRWXU}
  S_IRUSR = $0000100;
  {$EXTERNALSYM S_IRUSR}
  S_IWUSR = $0000080;
  {$EXTERNALSYM S_IWUSR}
  S_IXUSR = $0000040;
  {$EXTERNALSYM S_IXUSR}

  S_IRWXG = $0000038;    // mask for group permissions
  {$EXTERNALSYM S_IRWXG}
  S_IRGRP = $0000020;
  {$EXTERNALSYM S_IRGRP}
  S_IWGRP = $0000010;
  {$EXTERNALSYM S_IWGRP}
  S_IXGRP = $0000008;
  {$EXTERNALSYM S_IXGRP}

  S_IRWXO = $0000007;    // mask for permissions for others
  {$EXTERNALSYM S_IRWXO}
  S_IROTH = $0000004;
  {$EXTERNALSYM S_IROTH}
  S_IWOTH = $0000002;
  {$EXTERNALSYM S_IWOTH}
  S_IXOTH = $0000001;
  {$EXTERNALSYM S_IXOTH}

  // acl-flags
  SFX_ACL_CONTROL_INCLUDED      = $00000001;
  SFX_ACL_CONTROL_PRESENT       = $00000002;
  SFX_ACL_CONTROL_INHERITED     = $00000004;
  SFX_ACL_AUDIT_ALARM_INCLUDED  = $00000010;
  SFX_ACL_AUDIT_ALARM_INHERITED = $00000020;

  // ace-type
  ACE4_ACCESS_ALLOWED_ACE_TYPE = $00000000;
  ACE4_ACCESS_DENIED_ACE_TYPE  = $00000001;
  ACE4_SYSTEM_AUDIT_ACE_TYPE   = $00000002;
  ACE4_SYSTEM_ALARM_ACE_TYPE   = $00000003;

  // ace-flags
  ACE4_FILE_INHERIT_ACE           = $00000001;
  ACE4_DIRECTORY_INHERIT_ACE      = $00000002;
  ACE4_NO_PROPAGATE_INHERIT_ACE   = $00000004;
  ACE4_INHERIT_ONLY_ACE           = $00000008;
  ACE4_SUCCESSFUL_ACCESS_ACE_FLAG = $00000010;
  ACE4_FAILED_ACCESS_ACE_FLAG     = $00000020;
  ACE4_IDENTIFIER_GROUP           = $00000040;

  // ace-mask (desired-access)
  ACE4_READ_DATA         = $00000001;
  ACE4_LIST_DIRECTORY    = $00000001;
  ACE4_WRITE_DATA        = $00000002;
  ACE4_ADD_FILE          = $00000002;
  ACE4_APPEND_DATA       = $00000004;
  ACE4_ADD_SUBDIRECTORY  = $00000004;
  ACE4_READ_NAMED_ATTRS  = $00000008;
  ACE4_WRITE_NAMED_ATTRS = $00000010;
  ACE4_EXECUTE           = $00000020;
  ACE4_DELETE_CHILD      = $00000040;
  ACE4_READ_ATTRIBUTES   = $00000080;
  ACE4_WRITE_ATTRIBUTES  = $00000100;
  ACE4_DELETE            = $00010000;
  ACE4_READ_ACL          = $00020000;
  ACE4_WRITE_ACL         = $00040000;
  ACE4_WRITE_OWNER       = $00080000;
  ACE4_SYNCHRONIZE       = $00100000;

  // attrib-bits
  SSH_FILEXFER_ATTR_FLAGS_READONLY         = $00000001;
  SSH_FILEXFER_ATTR_FLAGS_SYSTEM           = $00000002;
  SSH_FILEXFER_ATTR_FLAGS_HIDDEN           = $00000004;
  SSH_FILEXFER_ATTR_FLAGS_CASE_INSENSITIVE = $00000008;
  SSH_FILEXFER_ATTR_FLAGS_ARCHIVE          = $00000010;
  SSH_FILEXFER_ATTR_FLAGS_ENCRYPTED        = $00000020;
  SSH_FILEXFER_ATTR_FLAGS_COMPRESSED       = $00000040;
  SSH_FILEXFER_ATTR_FLAGS_SPARSE           = $00000080;
  SSH_FILEXFER_ATTR_FLAGS_APPEND_ONLY      = $00000100;
  SSH_FILEXFER_ATTR_FLAGS_IMMUTABLE        = $00000200;
  SSH_FILEXFER_ATTR_FLAGS_SYNC             = $00000400;
  SSH_FILEXFER_ATTR_FLAGS_TRANSLATION_ERR  = $00000800;

  // text-hint
  SSH_FILEXFER_ATTR_KNOWN_TEXT     = $00;
  SSH_FILEXFER_ATTR_GUESSED_TEXT   = $01;
  SSH_FILEXFER_ATTR_KNOWN_BINARY   = $02;
  SSH_FILEXFER_ATTR_GUESSED_BINARY = $03;

  // rename flags
  SSH_FXF_RENAME_OVERWRITE = $00000001;
  SSH_FXF_RENAME_ATOMIC    = $00000002;
  SSH_FXF_RENAME_NATIVE    = $00000004;

  // realpath control-byte
  SSH_FXP_REALPATH_NO_CHECK    = $01;
  SSH_FXP_REALPATH_STAT_IF     = $02;
  SSH_FXP_REALPATH_STAT_ALWAYS = $03;

  // acl-supported
  SSH_ACL_CAP_ALLOW               = $00000001;
  SSH_ACL_CAP_DENY                = $00000002;
  SSH_ACL_CAP_AUDIT               = $00000004;
  SSH_ACL_CAP_ALARM               = $00000008;
  SSH_ACL_CAP_INHERIT_ACCESS      = $00000010;
  SSH_ACL_CAP_INHERIT_AUDIT_ALARM = $00000020;

  // Error codes
  SSH_FX_OK                       = 0;
  SSH_FX_EOF                      = 1;
  SSH_FX_NO_SUCH_FILE             = 2;
  SSH_FX_PERMISSION_DENIED        = 3;
  SSH_FX_FAILURE                  = 4;
  SSH_FX_BAD_MESSAGE              = 5;
  SSH_FX_NO_CONNECTION            = 6;
  SSH_FX_CONNECTION_LOST          = 7;
  SSH_FX_OP_UNSUPPORTED           = 8;
  SSH_FX_INVALID_HANDLE           = 9;
  SSH_FX_NO_SUCH_PATH             = 10;
  SSH_FX_FILE_ALREADY_EXISTS      = 11;
  SSH_FX_WRITE_PROTECT            = 12;
  SSH_FX_NO_MEDIA                 = 13;
  SSH_FX_NO_SPACE_ON_FILESYSTEM   = 14;
  SSH_FX_QUOTA_EXCEEDED           = 15;
  SSH_FX_UNKNOWN_PRINCIPAL        = 16;
  SSH_FX_LOCK_CONFLICT            = 17;
  SSH_FX_DIR_NOT_EMPTY            = 18;
  SSH_FX_NOT_A_DIRECTORY          = 19;
  SSH_FX_INVALID_FILENAME         = 20;
  SSH_FX_LINK_LOOP                = 21;
  SSH_FX_CANNOT_DELETE            = 22;
  SSH_FX_INVALID_PARAMETER        = 23;
  SSH_FX_FILE_IS_A_DIRECTORY      = 24;
  SSH_FX_BYTE_RANGE_LOCK_CONFLICT = 25;
  SSH_FX_BYTE_RANGE_LOCK_REFUSED  = 26;
  SSH_FX_DELETE_PENDING           = 27;
  SSH_FX_FILE_CORRUPT             = 28;
  SSH_FX_OWNER_INVALID            = 29;
  SSH_FX_GROUP_INVALID            = 30;
  SSH_FX_NO_MATCHING_BYTE_RANGE_LOCK = 31;

type
  TScSFTPErrorCode = (
    erOk, erEof, erNoSuchFile, erPermissionDenied,
    erFailure, erBadMessage, erNoConnection,
    erConnectionLost, erOpUnsupported, erInvalidHandle,
    erNoSuchPath, erFileAlreadyExists, erWriteProtect,
    erNoMedia, erNoSpaceOnFilesystem, erQuotaExceeded,
    erUnknownPrincipal, erLockConflict, erDirNotEmpty,
    erNotADirectory, erInvalidFilename, erLinkLoop,
    erCannotDelete, erInvalidParameter, erFileIsADirectory,
    erByteRangeLockConflict, erByteRangeLockRefused,
    erDeletePending, erFileCorrupt, erOwnerInvalid,
    erGroupInvalid);

const
  SFTPErrorCodes: array[TScSFTPErrorCode] of integer = (
    SSH_FX_OK, SSH_FX_EOF, SSH_FX_NO_SUCH_FILE, SSH_FX_PERMISSION_DENIED,
    SSH_FX_FAILURE, SSH_FX_BAD_MESSAGE, SSH_FX_NO_CONNECTION,
    SSH_FX_CONNECTION_LOST, SSH_FX_OP_UNSUPPORTED, SSH_FX_INVALID_HANDLE,
    SSH_FX_NO_SUCH_PATH, SSH_FX_FILE_ALREADY_EXISTS, SSH_FX_WRITE_PROTECT,
    SSH_FX_NO_MEDIA, SSH_FX_NO_SPACE_ON_FILESYSTEM, SSH_FX_QUOTA_EXCEEDED,
    SSH_FX_UNKNOWN_PRINCIPAL, SSH_FX_LOCK_CONFLICT, SSH_FX_DIR_NOT_EMPTY,
    SSH_FX_NOT_A_DIRECTORY, SSH_FX_INVALID_FILENAME, SSH_FX_LINK_LOOP,
    SSH_FX_CANNOT_DELETE, SSH_FX_INVALID_PARAMETER, SSH_FX_FILE_IS_A_DIRECTORY,
    SSH_FX_BYTE_RANGE_LOCK_CONFLICT, SSH_FX_BYTE_RANGE_LOCK_REFUSED,
    SSH_FX_DELETE_PENDING, SSH_FX_FILE_CORRUPT, SSH_FX_OWNER_INVALID,
    SSH_FX_GROUP_INVALID);

  SFTPErrorMessages: array[TScSFTPErrorCode] of string = (
    'Success', 'End of file', 'No such file', 'Permission denied',
    'Failure', 'Bad message', 'No_connection',
    'Connection lost', 'Operation unsupported', 'Invalid handle',
    'No such path', 'File already exists', 'Write protect',
    'No media', 'No space on filesystem', 'Quota exceeded',
    'Unknown principal', 'Lock conflict', 'Directory not empty',
    'Not a directory', 'Invalid filename', 'Link loop',
    'Cannot delete', 'Invalid parameter', 'File is a directory',
    'Byte range lock conflict', 'Byte range lock refused',
    'Delete pending', 'File corrupt', 'Owner invalid',
    'Group invalid');

type
  SFTPPacketType = type byte;

const
  MAX_SFTP_PACKET_LENGTH = 2 * 1024 * 1024 + 32 * 1024; // 2Mb + 32Kb

implementation

end.
