// CodeGear C++Builder
// Copyright (c) 1995, 2022 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'FMXTMSFNCWebSocketPkgDXE14.dpk' rev: 35.00 (Windows)

#ifndef Fmxtmsfncwebsocketpkgdxe14HPP
#define Fmxtmsfncwebsocketpkgdxe14HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMX.TMSFNCWebSocketClient.hpp>
#include <FMX.TMSFNCWebSocketClientReg.hpp>
#include <FMX.TMSFNCWebSocketCommon.hpp>
#include <FMX.TMSFNCWebSocketServer.hpp>
#include <FMX.TMSFNCWebSocketServerReg.hpp>
#include <FMX.TMSFNCWhatsAppReceiver.hpp>
#include <FMX.TMSFNCWhatsAppReceiverReg.hpp>
#include <FMX.TMSFNCWhatsAppServer.hpp>
#include <FMX.TMSFNCWhatsAppServerReg.hpp>
#include <System.Types.hpp>	// (rtl)
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.Messages.hpp>	// (rtl)
#include <System.SysConst.hpp>	// (rtl)
#include <Winapi.ImageHlp.hpp>	// (rtl)
#include <Winapi.SHFolder.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.RTLConsts.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <Winapi.ActiveX.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Hash.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Generics.Collections.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Diagnostics.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <IdException.hpp>	// (IndySystem)
#include <System.SyncObjs.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <IdResourceStrings.hpp>	// (IndySystem)
#include <IdStreamVCL.hpp>	// (IndySystem)
#include <IdStream.hpp>	// (IndySystem)
#include <System.StrUtils.hpp>	// (rtl)
#include <IdGlobal.hpp>	// (IndySystem)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <IdWinsock2.hpp>	// (IndySystem)
#include <IdWship6.hpp>	// (IndySystem)
#include <IdStackConsts.hpp>	// (IndySystem)
#include <IdStackBSDBase.hpp>	// (IndySystem)
#include <IdIDN.hpp>	// (IndySystem)
#include <Winapi.WinSock.hpp>	// (rtl)
#include <Winapi.IpTypes.hpp>	// (rtl)
#include <Winapi.IpRtrMib.hpp>	// (rtl)
#include <Winapi.IpExport.hpp>	// (rtl)
#include <Winapi.IpHlpApi.hpp>	// (rtl)
#include <IdStackWindows.hpp>	// (IndySystem)
#include <IdStack.hpp>	// (IndySystem)
#include <IdBaseComponent.hpp>	// (IndySystem)
#include <IdComponent.hpp>	// (IndySystem)
#include <IdExceptionCore.hpp>	// (IndyCore)
#include <IdResourceStringsCore.hpp>	// (IndyCore)
#include <IdBuffer.hpp>	// (IndyCore)
#include <IdIntercept.hpp>	// (IndyCore)
#include <IdAntiFreezeBase.hpp>	// (IndySystem)
#include <IdIOHandler.hpp>	// (IndyCore)
#include <IdSocketHandle.hpp>	// (IndyCore)
#include <IdCustomTransparentProxy.hpp>	// (IndyCore)
#include <IdAssignedNumbers.hpp>	// (IndyCore)
#include <IdIPAddress.hpp>	// (IndyCore)
#include <IdTCPClient.hpp>	// (IndyCore)
#include <IdIOHandlerStack.hpp>	// (IndyCore)
#include <IdSocks.hpp>	// (IndyCore)
#include <IdIOHandlerSocket.hpp>	// (IndyCore)
#include <IdReply.hpp>	// (IndyCore)
#include <IdReplyRFC.hpp>	// (IndyCore)
#include <IdTCPConnection.hpp>	// (IndyCore)
#include <IdCTypes.hpp>	// (IndySystem)
#include <IdResourceStringsProtocols.hpp>	// (IndyProtocols)
#include <IdFIPS.hpp>	// (IndyProtocols)
#include <IdCharsets.hpp>	// (IndyProtocols)
#include <Winapi.CommCtrl.hpp>	// (rtl)
#include <Winapi.Qos.hpp>	// (rtl)
#include <Winapi.Winsock2.hpp>	// (rtl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Winapi.RegStr.hpp>	// (rtl)
#include <Winapi.WinInet.hpp>	// (rtl)
#include <Winapi.UrlMon.hpp>	// (rtl)
#include <Winapi.ObjectArray.hpp>	// (rtl)
#include <Winapi.StructuredQueryCondition.hpp>	// (rtl)
#include <Winapi.PropSys.hpp>	// (rtl)
#include <Winapi.MSXMLIntf.hpp>	// (rtl)
#include <Winapi.ShlObj.hpp>	// (rtl)
#include <Winapi.KnownFolders.hpp>	// (rtl)
#include <System.Masks.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <IdGlobalProtocols.hpp>	// (IndyProtocols)
#include <IdResourceStringsOpenSSL.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSLHeaders.hpp>	// (IndyProtocols)
#include <IdYarn.hpp>	// (IndyCore)
#include <IdTask.hpp>	// (IndyCore)
#include <IdThreadSafe.hpp>	// (IndyCore)
#include <IdContext.hpp>	// (IndyCore)
#include <IdSchedulerOfThread.hpp>	// (IndyCore)
#include <IdThread.hpp>	// (IndyCore)
#include <IdScheduler.hpp>	// (IndyCore)
#include <IdServerIOHandler.hpp>	// (IndyCore)
#include <IdServerIOHandlerSocket.hpp>	// (IndyCore)
#include <IdServerIOHandlerStack.hpp>	// (IndyCore)
#include <IdGlobalCore.hpp>	// (IndyCore)
#include <IdSchedulerOfThreadDefault.hpp>	// (IndyCore)
#include <IdCustomTCPServer.hpp>	// (IndyCore)
#include <IdTCPServer.hpp>	// (IndyCore)
#include <IdSSL.hpp>	// (IndyProtocols)
#include <IdUriUtils.hpp>	// (IndyProtocols)
#include <IdURI.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSL.hpp>	// (IndyProtocols)
#include <IdHeaderList.hpp>	// (IndyProtocols)
#include <IdCookie.hpp>	// (IndyProtocols)
#include <IdCoder.hpp>	// (IndyProtocols)
#include <IdCoder3to4.hpp>	// (IndyProtocols)
#include <IdCoderMIME.hpp>	// (IndyProtocols)
#include <IdAuthentication.hpp>	// (IndyProtocols)
#include <IdHTTPHeaderInfo.hpp>	// (IndyProtocols)
#include <IdCustomHTTPServer.hpp>	// (IndyProtocols)
#include <IdHTTPServer.hpp>	// (IndyProtocols)
#include <System.Actions.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Math.Vectors.hpp>	// (rtl)
#include <System.ImageList.hpp>	// (rtl)
#include <FMX.Consts.hpp>	// (fmx)
#include <System.Win.Devices.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <FMX.Surfaces.hpp>	// (fmx)
#include <System.Win.Crtl.hpp>	// (rtl)
#include <System.RegularExpressionsAPI.hpp>	// (rtl)
#include <System.RegularExpressionsConsts.hpp>	// (rtl)
#include <System.RegularExpressionsCore.hpp>	// (rtl)
#include <System.RegularExpressions.hpp>	// (rtl)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <System.Analytics.hpp>	// (rtl)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.DialogService.Sync.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.ImgList.hpp>	// (fmx)
#include <Winapi.DxgiFormat.hpp>	// (rtl)
#include <Winapi.Wincodec.hpp>	// (rtl)
#include <Winapi.MultiMon.hpp>	// (rtl)
#include <Winapi.DXTypes.hpp>	// (rtl)
#include <Winapi.DxgiType.hpp>	// (rtl)
#include <Winapi.DXGI.hpp>	// (rtl)
#include <Winapi.D3DCommon.hpp>	// (rtl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Winapi.Imm.hpp>	// (rtl)
#include <System.Win.ComConst.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Winapi.ShellScaling.hpp>	// (rtl)
#include <FMX.Helpers.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.AcceleratorKey.hpp>	// (fmx)
#include <FMX.Objects.hpp>	// (fmx)
#include <FMX.DialogService.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <FMX.Materials.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Materials.Canvas.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.ZOrder.hpp>	// (fmx)
#include <FMX.ZOrder.Win.hpp>	// (fmx)
#include <Winapi.CommDlg.hpp>	// (rtl)
#include <Winapi.MMSystem.hpp>	// (rtl)
#include <Winapi.WinSpool.hpp>	// (rtl)
#include <Winapi.DirectDraw.hpp>	// (rtl)
#include <Winapi.GDIPAPI.hpp>	// (rtl)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <Winapi.GDIPUTIL.hpp>	// (rtl)
#include <FMX.Canvas.GDIP.hpp>	// (fmx)
#include <FMX.Printer.Win.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.hpp>	// (fmx)
#include <FMX.StdActns.hpp>	// (fmx)
#include <FMX.Presentation.Messages.hpp>	// (fmx)
#include <FMX.Controls.Model.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Presentation.Style.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.Controls.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.hpp>	// (fmx)
#include <FMX.Presentation.Style.Common.hpp>	// (fmx)
#include <FMX.Presentation.Win.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Switch.Win.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.Clipboard.Win.hpp>	// (fmx)
#include <FMX.Clipboard.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.SpellChecker.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.Win.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.Dialogs.Default.hpp>	// (fmx)
#include <FMX.DialogHelper.hpp>	// (fmx)
#include <FMX.Dialogs.Win.hpp>	// (fmx)
#include <Winapi.D3D10.hpp>	// (rtl)
#include <Winapi.D3D10_1.hpp>	// (rtl)
#include <FMX.Canvas.D2D.hpp>	// (fmx)
#include <Winapi.Direct3D9.hpp>	// (rtl)
#include <FMX.Context.DX9.hpp>	// (fmx)
#include <Winapi.D3D11.hpp>	// (rtl)
#include <FMX.Context.DX11.hpp>	// (fmx)
#include <FMX.Forms.Border.hpp>	// (fmx)
#include <FMX.Forms.Border.Win.hpp>	// (fmx)
#include <Winapi.TpcShrd.hpp>	// (rtl)
#include <Winapi.MsInkAut.hpp>	// (rtl)
#include <Winapi.Manipulations.hpp>	// (rtl)
#include <Winapi.RtsCom.hpp>	// (rtl)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.Gestures.Win.hpp>	// (fmx)
#include <FMX.MultiTouch.hpp>	// (fmx)
#include <FMX.MultiTouch.Win.hpp>	// (fmx)
#include <System.Win.StdVCL.hpp>	// (rtl)
#include <System.Win.OleControls.hpp>	// (rtl)
#include <System.Win.OleServers.hpp>	// (rtl)
#include <System.Win.InternetExplorer.hpp>	// (rtl)
#include <System.Win.IEInterfaces.hpp>	// (rtl)
#include <Winapi.WebView2.hpp>	// (rtl)
#include <Winapi.EdgeUtils.hpp>	// (rtl)
#include <FMX.Controls.Ole.hpp>	// (fmx)
#include <FMX.WebBrowser.Win.hpp>	// (fmx)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.KeyMapping.hpp>	// (fmx)
#include <FMX.AcceleratorKey.Win.hpp>	// (fmx)
#include <FMX.Platform.Screen.Win.hpp>	// (fmx)
#include <FMX.Platform.SaveState.Win.hpp>	// (fmx)
#include <FMX.Platform.Device.Win.hpp>	// (fmx)
#include <FMX.Platform.Metrics.Win.hpp>	// (fmx)
#include <FMX.ListBox.Selection.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.Default.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.Win.hpp>	// (fmx)
#include <FMX.Platform.Timer.Win.hpp>	// (fmx)
#include <FMX.Platform.Logger.Win.hpp>	// (fmx)
#include <FMX.Platform.Menu.Win.hpp>	// (fmx)
#include <FMX.Platform.Win.hpp>	// (fmx)
#include <FMX.StrokeBuilder.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <FMX.Platform.Common.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.ActnList.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <System.JSONConsts.hpp>	// (rtl)
#include <System.JSON.hpp>	// (rtl)
#include <System.NetEncoding.hpp>	// (rtl)
#include <FMX.TMSFNCUtils.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCJSONReader.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCJSONWriter.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCPersistence.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGDIPlusApi.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGDIPlusClasses.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGraphicsTypes.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCBitmapContainer.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCHTMLEngine.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGraphics.General.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGraphics.Win.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGraphics.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <Xml.XMLConst.hpp>	// (xmlrtl)
#include <Winapi.msxml.hpp>	// (rtl)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <Xml.XMLIntf.hpp>	// (xmlrtl)
#include <Xml.XMLSchemaTags.hpp>	// (xmlrtl)
#include <Xml.XMLSchema.hpp>	// (xmlrtl)
#include <Xml.xmlutil.hpp>	// (xmlrtl)
#include <Xml.XMLDoc.hpp>	// (xmlrtl)
#include <FMX.TMSFNCStyles.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCGraphicsSVGEngine.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCTypes.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <FMX.TMSFNCCustomComponent.hpp>	// (FMXTMSFNCCorePkgDXE14)
#include <IdHash.hpp>	// (IndyProtocols)
#include <IdHashSHA.hpp>	// (IndyProtocols)
// PRG_EXT: .bpl
// BPI_DIR: C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp\Win64
// OBJ_DIR: C:\Program Files (x86)\Embarcadero\Componentes\TMS FNC WebSocket\Win64\Release
// OBJ_EXT: .o

//-- user supplied -----------------------------------------------------------

namespace Fmxtmsfncwebsocketpkgdxe14
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Fmxtmsfncwebsocketpkgdxe14 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_FMXTMSFNCWEBSOCKETPKGDXE14)
using namespace Fmxtmsfncwebsocketpkgdxe14;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Fmxtmsfncwebsocketpkgdxe14HPP
