{********************************************************************}
{                                                                    }
{ written by TMS Software                                            }
{            copyright © 2018                                        }
{            Email : info@tmssoftware.com                            }
{            Web : http://www.tmssoftware.com                        }
{                                                                    }
{ The source code is given as is. The author is not responsible      }
{ for any possible damage done due to the use of this code.          }
{ The complete source code remains property of the author and may    }
{ not be distributed, published, given or sold in any form as such.  }
{ No parts of the source code can be included in any other component }
{ or application without written authorization of the author.        }
{********************************************************************}

unit WEBLib.TMSFNCCoreWEBReg;

{$I WEBLib.TMSFNCDefines.inc}

interface

implementation

uses
  Classes, WEBLib.DesignIntf, WEBLib.TMSFNCBitmapContainer, WEBLib.TMSFNCPopup, WEBLIB.TMSFNCStyles,
  WEBLib.TMSFNCScrollBar, WEBLib.TMSFNCGraphicsPDFEngine, WEBLIB.TMSFNCPDFLib;

const
  TTMSFNCBITMAPCONTAINER_ICON =
    'data:image/bmp;base64,Qk12BgAAAAAAADYEAAAoAAAAGAAAABgAAAABAAgAAAAAAEACAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmAAAgQAAAIGAAACCAAAAgoAAAIMAAACDgAABAAAAAQCAAAEBAAABAYAAAQIAAAECgAABAwAAAQOAAAGAAAABgIAAAYEAAAGBgAABggAAAYKAAA'
    + 'GDAAABg4AAAgAAAAIAgAACAQAAAgGAAAICAAACAoAAAgMAAAIDgAACgAAAAoCAAAKBAAACgYAAAoIAAAKCgAACgwAAAoOAAAMAAAADAIAAAwEAAAMBgAADAgAAAwKAAAMDAAADA4AAA4AAAAOAgAADgQAAA4GAAAOCAAADgoAAA4MAAAODgAEAAAABAACAAQABAAEAAYABAAIAAQACgAEAAwABAAOAAQCAAAEAgIABAIEAAQCBgAEAggABAIKAA'
    + 'QCDAAEAg4ABAQAAAQEAgAEBAQABAQGAAQECAAEBAoABAQMAAQEDgAEBgAABAYCAAQGBAAEBgYABAYIAAQGCgAEBgwABAYOAAQIAAAECAIABAgEAAQIBgAECAgABAgKAAQIDAAECA4ABAoAAAQKAgAECgQABAoGAAQKCAAECgoABAoMAAQKDgAEDAAABAwCAAQMBAAEDAYABAwIAAQMCgAEDAwABAwOAAQOAAAEDgIABA4EAAQOBgAEDggABA4KA'
    + 'AQODAAEDg4ACAAAAAgAAgAIAAQACAAGAAgACAAIAAoACAAMAAgADgAIAgAACAICAAgCBAAIAgYACAIIAAgCCgAIAgwACAIOAAgEAAAIBAIACAQEAAgEBgAIBAgACAQKAAgEDAAIBA4ACAYAAAgGAgAIBgQACAYGAAgGCAAIBgoACAYMAAgGDgAICAAACAgCAAgIBAAICAYACAgIAAgICgAICAwACAgOAAgKAAAICgIACAoEAAgKBgAICggACAoK'
    + 'AAgKDAAICg4ACAwAAAgMAgAIDAQACAwGAAgMCAAIDAoACAwMAAgMDgAIDgAACA4CAAgOBAAIDgYACA4IAAgOCgAIDgwACA4OAAwAAAAMAAIADAAEAAwABgAMAAgADAAKAAwADAAMAA4ADAIAAAwCAgAMAgQADAIGAAwCCAAMAgoADAIMAAwCDgAMBAAADAQCAAwEBAAMBAYADAQIAAwECgAMBAwADAQOAAwGAAAMBgIADAYEAAwGBgAMBggADAY'
    + 'KAAwGDAAMBg4ADAgAAAwIAgAMCAQADAgGAAwICAAMCAoADAgMAAwIDgAMCgAADAoCAAwKBAAMCgYADAoIAAwKCgAMCgwADAoOAAwMAAAMDAIADAwEAAwMBgAMDAgADAwKAA8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AP3/////////////////////////////////////////////////////////////////////'
    + '//////////////////////////+kpKSkpKSkpKSkpKSkpKSkpKSkpKSk//+k//////////////////////////+k//+k//////////////////////////+k//+k//////////////////////////+k//+k////pKSkpKSkpKSkpKSkpKSk//+k//+k/////6SkpKSkpKSkpKSkpKT///+k//+k//////+kpKSkpKSkpKSkpP////+k//+k///'
    + '/////pKSkpKSkpKSkpP////+k//+k/////////6SkpKSkpKSk//////+k//+k/////////////6SkpKT///////+k//+k/////6Sk//////+kpKT///////+k//+k////pKSkpP//////pP////////+k//+k////pKSkpP////////////////+k//+k/////6Sk//////////////////+k//+k//////////////////////////+k//+k//'
    + '////////////////////////+k//+k//////////////////////////+k//+kpKSkpKSkpKSkpKSkpKSkpKSkpKSk/////////////////////////////////////////////////////////////////////////////////////////////////w';
  TTMSFNCPOPUP_ICON =
    'data:image/bmp;base64,Qk12BgAAAAAAADYEAAAoAAAAGAAAABgAAAABAAgAAAAAAEACAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmAAAgQAAAIGAAACCAAAAgoAAAIMAAACDgAABAAAAAQCAAAEBAAABAYAAAQIAAAECgAABAwAAAQOAAAGAAAABgIAAAYEAAAGBgAABggAAAYKAAA'
    + 'GDAAABg4AAAgAAAAIAgAACAQAAAgGAAAICAAACAoAAAgMAAAIDgAACgAAAAoCAAAKBAAACgYAAAoIAAAKCgAACgwAAAoOAAAMAAAADAIAAAwEAAAMBgAADAgAAAwKAAAMDAAADA4AAA4AAAAOAgAADgQAAA4GAAAOCAAADgoAAA4MAAAODgAEAAAABAACAAQABAAEAAYABAAIAAQACgAEAAwABAAOAAQCAAAEAgIABAIEAAQCBgAEAggABAIKAA'
    + 'QCDAAEAg4ABAQAAAQEAgAEBAQABAQGAAQECAAEBAoABAQMAAQEDgAEBgAABAYCAAQGBAAEBgYABAYIAAQGCgAEBgwABAYOAAQIAAAECAIABAgEAAQIBgAECAgABAgKAAQIDAAECA4ABAoAAAQKAgAECgQABAoGAAQKCAAECgoABAoMAAQKDgAEDAAABAwCAAQMBAAEDAYABAwIAAQMCgAEDAwABAwOAAQOAAAEDgIABA4EAAQOBgAEDggABA4KA'
    + 'AQODAAEDg4ACAAAAAgAAgAIAAQACAAGAAgACAAIAAoACAAMAAgADgAIAgAACAICAAgCBAAIAgYACAIIAAgCCgAIAgwACAIOAAgEAAAIBAIACAQEAAgEBgAIBAgACAQKAAgEDAAIBA4ACAYAAAgGAgAIBgQACAYGAAgGCAAIBgoACAYMAAgGDgAICAAACAgCAAgIBAAICAYACAgIAAgICgAICAwACAgOAAgKAAAICgIACAoEAAgKBgAICggACAoK'
    + 'AAgKDAAICg4ACAwAAAgMAgAIDAQACAwGAAgMCAAIDAoACAwMAAgMDgAIDgAACA4CAAgOBAAIDgYACA4IAAgOCgAIDgwACA4OAAwAAAAMAAIADAAEAAwABgAMAAgADAAKAAwADAAMAA4ADAIAAAwCAgAMAgQADAIGAAwCCAAMAgoADAIMAAwCDgAMBAAADAQCAAwEBAAMBAYADAQIAAwECgAMBAwADAQOAAwGAAAMBgIADAYEAAwGBgAMBggADAY'
    + 'KAAwGDAAMBg4ADAgAAAwIAgAMCAQADAgGAAwICAAMCAoADAgMAAwIDgAMCgAADAoCAAwKBAAMCgYADAoIAAwKCgAMCgwADAoOAAwMAAAMDAIADAwEAAwMBgAMDAgADAwKAA8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AP3/////////////////////////////////////////////////////////////////////'
    + '//////////////////////////+kpKSkpKSkpKSkpKSkpKSkpKSkpKSk//+k//////////////////////////+k//+k//////////////////////////+k//+k//////////+kpKT///////////+k//+k//////////+kpKT///////////+k//+k//////////+kpKT///////////+k//+k//////////+kpKT///////////+k//+k///'
    + '///////+kpKT///////////+k//+k//////////+kpKT///////////+k//+k//////////+kpKT///////////+k//+k//////////+kpKT///////////+k//+k//////+kpKSkpKSkpKT///////+k//+k////////pKSkpKSkpP////////+k//+k/////////6SkpKSk//////////+k//+k//////////+kpKT///////////+k//+k//'
    + '//////////pP////////////+k//+k//////////////////////////+k//+kpKSkpKSkpKSkpKSkpKSkpKSkpKSk/////////////////////////////////////////////////////////////////////////////////////////////////w';
  TTMSFNCSCROLLBAR_ICON =
    'data:image/bmp;base64,Qk12BgAAAAAAADYEAAAoAAAAGAAAABgAAAABAAgAAAAAAEACAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmAAAgQAAAIGAAACCAAAAgoAAAIMAAACDgAABAAAAAQCAAAEBAAABAYAAAQIAAAECgAABAwAAAQOAAAGAAAABgIAAAYEAAAGBgAABggAAAYKAAA'
    + 'GDAAABg4AAAgAAAAIAgAACAQAAAgGAAAICAAACAoAAAgMAAAIDgAACgAAAAoCAAAKBAAACgYAAAoIAAAKCgAACgwAAAoOAAAMAAAADAIAAAwEAAAMBgAADAgAAAwKAAAMDAAADA4AAA4AAAAOAgAADgQAAA4GAAAOCAAADgoAAA4MAAAODgAEAAAABAACAAQABAAEAAYABAAIAAQACgAEAAwABAAOAAQCAAAEAgIABAIEAAQCBgAEAggABAIKAA'
    + 'QCDAAEAg4ABAQAAAQEAgAEBAQABAQGAAQECAAEBAoABAQMAAQEDgAEBgAABAYCAAQGBAAEBgYABAYIAAQGCgAEBgwABAYOAAQIAAAECAIABAgEAAQIBgAECAgABAgKAAQIDAAECA4ABAoAAAQKAgAECgQABAoGAAQKCAAECgoABAoMAAQKDgAEDAAABAwCAAQMBAAEDAYABAwIAAQMCgAEDAwABAwOAAQOAAAEDgIABA4EAAQOBgAEDggABA4KA'
    + 'AQODAAEDg4ACAAAAAgAAgAIAAQACAAGAAgACAAIAAoACAAMAAgADgAIAgAACAICAAgCBAAIAgYACAIIAAgCCgAIAgwACAIOAAgEAAAIBAIACAQEAAgEBgAIBAgACAQKAAgEDAAIBA4ACAYAAAgGAgAIBgQACAYGAAgGCAAIBgoACAYMAAgGDgAICAAACAgCAAgIBAAICAYACAgIAAgICgAICAwACAgOAAgKAAAICgIACAoEAAgKBgAICggACAoK'
    + 'AAgKDAAICg4ACAwAAAgMAgAIDAQACAwGAAgMCAAIDAoACAwMAAgMDgAIDgAACA4CAAgOBAAIDgYACA4IAAgOCgAIDgwACA4OAAwAAAAMAAIADAAEAAwABgAMAAgADAAKAAwADAAMAA4ADAIAAAwCAgAMAgQADAIGAAwCCAAMAgoADAIMAAwCDgAMBAAADAQCAAwEBAAMBAYADAQIAAwECgAMBAwADAQOAAwGAAAMBgIADAYEAAwGBgAMBggADAY'
    + 'KAAwGDAAMBg4ADAgAAAwIAgAMCAQADAgGAAwICAAMCAoADAgMAAwIDgAMCgAADAoCAAwKBAAMCgYADAoIAAwKCgAMCgwADAoOAAwMAAAMDAIADAwEAAwMBgAMDAgADAwKAA8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AP3//////////////////////////////////////////6SkpKSk////////////////////'
    + '/////6T///+k/////////////////////////6Sk/6Sk/////////////////////////6SkpKSk/////////////////////////6T///+k/////////////////////////6T///+k/////////////////////////6T///+k/////////////////////////6T///+k/////////////////////////6T///+k///////////////////'
    + '//////6T///+k/////////////////////////6T///+k/////////////////////////6SkpKSk/////////////////////////6SkpKSk/////////////////////////6SkpKSk/////////////////////////6T///+k/////////////////////////6T///+k/////////////////////////6T///+k//////////////////'
    + '///////6T///+k/////////////////////////6SkpKSk/////////////////////////6Sk/6Sk/////////////////////////6T///+k/////////////////////////6SkpKSk/////////////////////////////////////////////w';

  TTMSFNCGRAPHICSPDFIO_ICON = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAYUExU'+
    'Rf///4CAgP//AP8AAAD/ACBAwOAgAP8A/zPx7o4AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB7SURBVCjPlY6xDUMhDETthppE8PtkA8QEkbwAhVdw/fevcgYCtDmExONZcPRHHiMDnm/Pi4'+
    'hxtaHWusYcCkZTpAUsnx9ESiJxQmMRVw5ZIVwBimqTrvBPVtVVgWF2t6xxA7ez9mU9AwIZVpjQs01wO40dBgfDvjv4W2Zf9CobmjBSCe4AAAAASUVORK5CYII=';

  TTMSFNCPDFLIB_ICON = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAMUExURf///4CAgOAgAP8A/wHrgswAAAAJcEhZcwAADsMAAA7DAcdvqGQA'+
    'AABWSURBVCjPnY/BDYAwDANTT5Awgidg/+lInQoiBDxw1cfl3Ei1j4yoFKyZd4gClUZ4Nw3M/Kzl/MHcay/m3zZQKQNjHixQLoNp9e0NLGOq5Zu8u2DuIg/EIQZ/KErhagAAAABJRU5ErkJggg==';

  TTMSFNCSTYLESMANAGER_ICON = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjw'+
    'v8YQUAAAAwUExURYCAgP///8BggMBgQKBgQEBggIBggGBggKBggP/78OCggMCAQOCgQMDAwODAgMDcwJUPtS8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAABySURBVCjPY0'+
    'ABjIJwIADkCBmDgSKYIwzhGBLgiLi4OMM5oqGhoWbFZQhOaXF5I4QDskNKMBDBEcTGkd4NBhvBHKkzYLAQzJF9927NqXfvLoI5QPDmHMzVQPDnPBIHRQaFs+YULs6rdU'+
    'gc2YsQDgIwMAAAm0I0iGOFLYoAAAAASUVORK5CYII=';

procedure register;
begin
  RegisterComponents('TMS FNC UI', [TTMSFNCBitmapContainer, TTMSFNCGraphicsPDFIO, TTMSFNCPDFLIB, TTMSFNCPopup, TTMSFNCScrollBar, TTMSFNCStylesManager],
  [TTMSFNCBITMAPCONTAINER_ICON,  TTMSFNCGRAPHICSPDFIO_ICON, TTMSFNCPDFLIB_ICON, TTMSFNCPOPUP_ICON, TTMSFNCSCROLLBAR_ICON, TTMSFNCSTYLESMANAGER_ICON]);

  RegisterClass(TTMSFNCBitmapContainer);
  RegisterClass(TTMSFNCGraphicsPDFIO);
  RegisterClass(TTMSFNCPDFLib);
  RegisterClass(TTMSFNCPopup);
  RegisterClass(TTMSFNCScrollBar);
  RegisterClass(TTMSFNCStylesManager);
end;

initialization

begin
  register;
end;

end.
